name: sashimi
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pyqt = 5.12.3
  - numpy = 1.19.5
  - scipy
  - numba = 0.55.1
  - pandas
  - pytables = 3.6.1
  - ffmpeg
  - scikit-image
  - h5py
  - vispy = 0.6.6
