name: sashimi
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.6
  - appdirs=1.4.4=pyh9f0ad1d_0
  - blosc=1.21.0=h0e60522_0
  - brotli=1.0.9=h0e60522_4
  - brotlipy=0.7.0=py38h294d835_1001
  - bzip2=1.0.8=h8ffe710_4
  - ca-certificates=2020.12.5=h5b45459_0
  - cached-property=1.5.1=py_0
  - certifi=2020.12.5=py38haa244fe_1
  - cffi=1.14.4=py38hd8c33c5_1
  - chardet=4.0.0=py38haa244fe_1
  - charls=2.2.0=h39d44d4_0
  - cloudpickle=1.6.0=py_0
  - cryptography=3.3.1=py38hd8c33c5_1
  - cycler=0.10.0=py_2
  - cytoolz=0.11.0=py38h294d835_3
  - dask-core=2021.1.1=pyhd8ed1ab_0
  - decorator=4.4.2=py_0
  - ffmpeg=4.3.1=ha925a31_0
  - freetype=2.10.4=h546665d_1
  - freetype-py=2.2.0=pyh9f0ad1d_0
  - giflib=5.2.1=h8d14728_2
  - h5py=3.1.0=nompi_py38h022eade_100
  - hdf5=1.10.6=nompi_h5268f04_1114
  - icu=68.1=h0e60522_0
  - idna=2.10=pyh9f0ad1d_0
  - imagecodecs=2021.1.11=py38h1ceb79b_1
  - imageio=2.9.0=py_0
  - intel-openmp=2020.3=h57928b3_311
  - jpeg=9d=h8ffe710_0
  - jxrlib=1.1=h8ffe710_2
  - kiwisolver=1.3.1=py38hbd9d945_1
  - krb5=1.17.2=hbae68bd_0
  - lcms2=2.11=h6a326e1_1
  - lerc=2.2.1=h0e60522_0
  - libaec=1.0.4=h39d44d4_1
  - libblas=3.9.0=7_mkl
  - libcblas=3.9.0=7_mkl
  - libclang=11.0.1=default_h5c34c98_1
  - libcurl=7.71.1=h4b64cdc_8
  - libdeflate=1.7=h8ffe710_5
  - liblapack=3.9.0=7_mkl
  - libpng=1.6.37=h1d00b33_2
  - libssh2=1.9.0=hb06d900_5
  - libtiff=4.2.0=hc10be44_0
  - libwebp-base=1.2.0
  - libzopfli=1.0.3=h0e60522_0
  - llvmlite=0.35.0=py38h57a6900_1
  - lz4-c=1.9.3=h8ffe710_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - matplotlib-base=3.3.4=py38h34ddff4_0
  - mkl=2020.4=hb70f87d_311
  - mock=4.0.3=py38haa244fe_1
  - msys2-conda-epoch=20160418=1
  - networkx=2.5=py_0
  - numba=0.52.0=py38h4c96930_0
  - numexpr=2.7.2=py38h4c96930_0
  - numpy=1.19.5=py38h0cc643e_1
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=h48faf41_0
  - openssl=1.1.1i=h8ffe710_0
  - packaging=20.8=pyhd3deb0d_0
  - pandas=1.2.1=py38h4c96930_0
  - pillow=8.1.0=py38hf7ce48b_1
  - pip=21.0.1=pyhd8ed1ab_0
  - pooch=1.3.0=pyhd8ed1ab_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py38haa244fe_7
  - pyqtchart=5.12=py38h885f38d_7
  - pyqtwebengine=5.12.1=py38h885f38d_7
  - pyreadline=2.1=py38haa244fe_1003
  - pysocks=1.7.1=py38haa244fe_3
  - pytables=3.6.1=py38h153c448_3
  - python=3.8.6=h7840368_5_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytz=2021.1=pyhd8ed1ab_0
  - pywavelets=1.1.1=py38h347fdf6_3
  - pyyaml=5.4.1=py38h294d835_0
  - qt=5.12.9=h5909a2a_3
  - requests=2.25.1=pyhd3deb0d_0
  - scikit-image=0.18.1=py38h4c96930_0
  - scipy=1.6.0=py38h5f893b4_0
  - setuptools=49.6.0=py38haa244fe_3
  - six=1.15.0=pyh9f0ad1d_0
  - snappy=1.1.8=ha925a31_3
  - sqlite=3.34.0=h8ffe710_0
  - tifffile=2021.1.14=pyhd8ed1ab_0
  - tk=8.6.10=h8ffe710_1
  - toolz=0.11.1=py_0
  - tornado=6.1=py38h294d835_1
  - urllib3=1.26.3=pyhd8ed1ab_0
  - vc=14.2=hb210afc_2
  - vispy=0.6.6=py38h347fdf6_0
  - vs2015_runtime=14.28.29325=h5e1d092_0
  - wheel=0.36.2=pyhd3deb0d_0
  - win_inet_pton=1.1.0=py38haa244fe_2
  - wincertstore=0.2=py38haa244fe_1006
  - xz=5.2.5=h62dcd97_1
  - yaml=0.2.5=he774522_0
  - zfp=0.5.5=h0e60522_4
  - zlib=1.2.11=h62dcd97_1010
  - zstd=1.4.8=h4e2f164_1
  - pip:
    - alabaster==0.7.12
    - argon2-cffi==20.1.0
    - arrayqueues==1.2.0b0
    - async-generator==1.10
    - atomicwrites==1.4.0
    - attrs==20.3.0
    - babel==2.9.0
    - backcall==0.2.0
    - bleach==3.2.3
    - cachetools==4.2.1
    - cachey==0.2.1
    - click==7.1.2
    - colorama==0.4.4
    - cssselect==1.1.0
    - cssutils==1.0.2
    - defusedxml==0.6.0
    - docstring-parser==0.7.3
    - docutils==0.16
    - entrypoints==0.3
    - flammkuchen==0.9
    - heapdict==1.0.1
    - helpdev==0.7.1
    - imagesize==1.2.0
    - iniconfig==1.1.1
    - ipykernel==5.4.3
    - ipython==7.19.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.3
    - jedi==0.18.0
    - jinja2==2.11.3
    - jsonschema==3.2.0
    - jupyter-client==6.1.11
    - jupyter-core==4.7.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.0
    - lightparam==0.4.6
    - lxml==4.6.2
    - magicgui==0.2.6
    - markdown==3.2.2
    - markupsafe==1.1.1
    - mistune==0.8.4
    - napari==0.4.4
    - napari-console==0.0.3
    - napari-plugin-engine==0.1.9
    - napari-split-dataset==0.2.0
    - napari-svg==0.1.4
    - nbclient==0.5.1
    - nbconvert==6.0.7
    - nbformat==5.1.2
    - nest-asyncio==1.5.1
    - nidaqmx==0.5.7
    - notebook==6.2.0
    - numpydoc==1.1.0
    - pandocfilters==1.4.3
    - parso==0.8.1
    - pickleshare==0.7.5
    - pluggy==0.13.1
    - premailer==3.7.0
    - prometheus-client==0.9.0
    - prompt-toolkit==3.0.14
    - psutil==5.8.0
    - py==1.10.0
    - pydantic==1.8.2
    - pygments==2.7.4
    - pyopengl==3.1.5
    - pyqt5==5.15.2
    - pyqt5-sip==12.8.1
    - pyqtgraph==0.11.1
    - pyrsistent==0.17.3
    - pytest==6.2.2
    - pytest-qt==3.3.0
    - pyvisa==1.11.3
    - pywin32==300
    - pywinpty==0.5.7
    - pyzmq==22.0.2
    - qdarkstyle==2.7
    - qtconsole==5.0.2
    - qtpy==1.9.0
    - scopecuisine==0.1.3
    - send2trash==1.5.0
    - snowballstemmer==2.1.0
    - sphinx==3.4.3
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - split-dataset==0.3.0
    - terminado==0.9.2
    - testpath==0.4.4
    - toml==0.10.2
    - tqdm==4.61.0
    - traitlets==5.0.5
    - typing-extensions==3.10.0.0
    - visa==1.0.0
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
    - wrapt==1.12.1
    - yagmail==0.14.245
